FROM python:3.10-slim

RUN pip install --no-cache-dir mlflow==2.14.1 psycopg2-binary==2.9.9

EXPOSE 5000

CMD mlflow server \
    --backend-store-uri "${MLFLOW_BACKEND_STORE_URI}" \
    --default-artifact-root "${MLFLOW_ARTIFACT_ROOT}" \
    --host 0.0.0.0 \
    --port 5000
